### PR TITLE
Avoid using nodejs globals that would need to get shimmed.

### LINKED ISSUE #323: not compatible with angular-cli  6+
Angular 6+ `ng build` does not polyfill node globals and native apis, making it difficult to use this lib in an Angular 6+ project. 

See: https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

It would be cool if running `npm install stanza` alone provided a browser-ready module that can be imported without the need for the library consumer's module bundler to polyfill native node packages and globals.

### PR DESCRIPTION
**Pull request by legastero**
Should fix #323 unless there are other symbols causing problems.

Let me know if there's more I need to fix here @hansifer. It'll probably be this weekend before I can figure out enough Angular to test.

### CODE REVIEW

**Comment by legastero** [comment]
Still working through this one.

I've got all the hash/hmac modules sorted out locally now, but it looks like in the end the `Buffer` and `stream` modules will still need to get shimmed for the browser.

**Comment by kai670** [comment]
afaik you don't need any angular knowledge to reproduce this. Setting `node: false`,
inside `webpack.js` is enough to check it can be built without including node shims.

I can reproduce it with the next change:

```
diff --git a/webpack.config.js b/webpack.config.js
index 5c4f8c4..ead50fa 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -3,7 +3,7 @@ const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPl
 const Pkg = require('./package.json');
 
 module.exports = {
-    entry: './dist/npm/module.js',
+    entry: './dist/es/index.js',
 
     output: {
         filename: 'stanza.browser.js',
@@ -29,6 +29,7 @@ module.exports = {
             }
         ]
     },
+    node: false,
 
     plugins: [
         new BundleAnalyzerPlugin({
```

btw, problem also occurs in this branch

**Comment by legastero** [comment]
Rebased and pulled in changes I've been working on to not require as many node-assuming dependencies.

I got the @hansifer 's angular test repo working using this branch now, and with this snippet added to the polyfills:

```ts
(window as any).global = window;
(window as any).process = { version: '' };

import * as Buffer from 'buffer';
(window as any).Buffer = Buffer.Buffer;
```

Those bits are still needed to make the `readable-stream` dependency work, so that's probably as far as I can push things for now.

**Comment by kai670** [comment]
Sorry to bother you but after this merge I'm not able to build the project. Here is the output I get:

```
node scripts/build.js

dist/es/index.js → dist/es/index.module.js...
created dist/es/index.module.js in 1.2s

dist/es/index.js → dist/es/index-browser.module.js...
[!] Error: Export 'Hmac' is not defined
dist/es/lib/crypto/index-browser.js (92:15)
90:     ['sha512', SHA512]
91: ]);
92: export { Hash, Hmac };
                   ^
93: export function randomBytes(size) {
94:     const rawBytes = new Uint8Array(size);
Error: Export 'Hmac' is not defined
    at error (/home/andres/quobis_ws/stanza.io/node_modules/rollup/dist/rollup.js:3597:30)
    at Module.error (/home/andres/quobis_ws/stanza.io/node_modules/rollup/dist/rollup.js:14393:9)
    at tryParse (/home/andres/quobis_ws/stanza.io/node_modules/rollup/dist/rollup.js:14056:16)
    at Module.setSource (/home/andres/quobis_ws/stanza.io/node_modules/rollup/dist/rollup.js:14112:35)
    at /home/andres/quobis_ws/stanza.io/node_modules/rollup/dist/rollup.js:17516:20

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stanza@11.2.0 compile:rollup-browser: `rollup -c rollup-browser.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the stanza@11.2.0 compile:rollup-browser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/andres/.npm/_logs/2019-04-21T20_12_09_258Z-debug.log
child_process.js:656
    throw err;
    ^

Error: Command failed: npm run compile:rollup-browser

dist/es/index.js → dist/es/index-browser.module.js...
[!] Error: Export 'Hmac' is not defined
dist/es/lib/crypto/index-browser.js (92:15)
90:     ['sha512', SHA512]
91: ]);
92: export { Hash, Hmac };
                   ^
93: export function randomBytes(size) {
94:     const rawBytes = new Uint8Array(size);
Error: Export 'Hmac' is not defined
    at error (/home/andres/quobis_ws/stanza.io/node_modules/rollup/dist/rollup.js:3597:30)
    at Module.error (/home/andres/quobis_ws/stanza.io/node_modules/rollup/dist/rollup.js:14393:9)
    at tryParse (/home/andres/quobis_ws/stanza.io/node_modules/rollup/dist/rollup.js:14056:16)
    at Module.setSource (/home/andres/quobis_ws/stanza.io/node_modules/rollup/dist/rollup.js:14112:35)
    at /home/andres/quobis_ws/stanza.io/node_modules/rollup/dist/rollup.js:17516:20

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stanza@11.2.0 compile:rollup-browser: `rollup -c rollup-browser.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the stanza@11.2.0 compile:rollup-browser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/andres/.npm/_logs/2019-04-21T20_12_09_258Z-debug.log

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at Object.<anonymous> (/home/andres/quobis_ws/stanza.io/scripts/build.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

am I doing something wrong?

**Comment by legastero** [comment]
I think I see what is wrong. The `Hmac` class was getting exported as default by mistake, so I'll get that fixed now.

But even after completely wiping node modules and reinstalling to test the build, it didn't give me a build error about it. So I'm rather confused why I didn't run into this.

**Comment by legastero** [comment]
That _should_ be resolved now, @kai670. Thanks for alerting me on that one!

**Comment by kai670** [comment]
It's working now. Thanks!

**Comment by toriqo** [comment]
There is still something wrong but I can't figure out what. It's not working on websockets anymore, only BOSH. (It works correctly on Angular 5 with Typescript updated to 3.7.2 but not on Angular 8).
Also, in the `process` object `nextTick: () => { return null; }` needs to be added as well (polyfills.js) because the compiler complains about that as well and `(window as any).global = window` needs to be added to `index.html` otherwise the moment you add `import * as Buffer from 'buffer'; (window as any).Buffer = Buffer.Buffer;` to polyfills.js it complains about not finding `global` again... Any advice to make it work on websockets?

**Comment by liuhang-cn** [comment]
It still not work on browser. Some node variable still wrong.

**Pull request merged**
