### PR TITLE
emit chat/groupchat events for messages with oob but without body

### PR DESCRIPTION
**Pull request by kai670**

### CODE REVIEW

**Comment by legastero** [comment]
I'm ok with this, but I'm still a bit hesitant, since the `chat` and `groupchat` events have always specifically been for messages with body content. Could you elaborate on what you're making that needed this change?

**Comment by kai670** [comment]
When sending files using [XEP-0066: Out of Band Data](https://xmpp.org/extensions/xep-0066.html) I'm sending a message this way:
```sendMessage({to, type, markable: true, oob: {url, desc}});```

The only way this is notified in the destination, is in the `message` event unless an empty `body` is also included. In that case the `chat`/`groupchat` event is also emitted. So I think it makes sense emitting this events also if there is no body but there is an oob.

Another option could be creating new `chat:oob`/`groupchat:oob` events that will be triggered when oob is present but I think it will be much more confusing (both should be triggered if body and oob is present?) and I see no benefit.

**Comment by marc0s** [comment]
Related with this, I opened an issue with a very related question https://github.com/legastero/stanza.io/issues/275

**Comment by kai670** [comment]
I updated the code as I realised it was breaking the case of an empty string as body.

**Comment by marc0s** [comment]
I think that makes sense to also emit `chat`/`groupchat` for `<message />` stanzas with `oob` payload even if they have no body because:
* they are usually part of some ongoing conversation so emitting the same event "makes sense" (be it a chat or a groupchat), and
* other specific event would add extra logic to handle the case where both oob and body are present

**Pull request merged**
